# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
- feature/*

pr:
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  zig_version: master

steps:
- script: |
    export PYTHONIOENCODING=utf8
    wget $(curl -s 'https://ziglang.org/download/index.json' | python3 -c "import sys, json; print(json.load(sys.stdin)['$(zig_version)']['x86_64-linux']['tarball'])")
    tar -xvf zig*
  displayName: 'Download zig'

- script: zig*/zig build
  displayName: 'Build kernel'

- script: zig*/zig build test
  displayName: 'Unit tests'

- script: |
    sudo apt-get update
    sudo apt-get install qemu qemu-system --fix-missing
  displayName: 'Download qemu'

- script: |
    zig*/zig build test -Drt-test=true
  displayName: 'Runtime tests'
